version: '3.4'

services:
  
  bono-orders-infrastructure-sql-data:    
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: bono-orders-infrastructure-sql-data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=H@rd2103211943
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data   
    ports:
      - "1433:1433"
             
  bono-orders-api:
    image: bono-orders-api
    container_name: bono-orders-api
    build:
      context: ./orders-backend/src/
      dockerfile: 1-Api/Bono.Orders.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:    
      - bono-orders-infrastructure-sql-data  
  
  # bono-orders-test:
  #   image: bono-orders-test
  #   container_name: bono-orders-test
  #   build:
  #     context: ./orders-backend/src/
  #     dockerfile: 0-Test/Bono.Orders.Application.Tests/Dockerfile    
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - bono-orders-infrastructure-sql-data
  #     - bono-orders-api-task-Order      

volumes:
  mssql-server-linux-data: