apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders-frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-frontend
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
