apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orders-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orders-backend
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
