apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: v1
    app: orders-backend
  name: orders-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: orders-backend
  template:
    metadata:
      labels:
        app: orders-backend
        version: v1
        stack: echo
        interface: rest
        language: csharp
    spec:
      containers:
        - image: richiebono/bono-orders-api:latest
          imagePullPolicy: IfNotPresent 
          envFrom:
            - configMapRef:
                name: orders-config
          resources:
            requests:
              memory: "5Mi"
              cpu: "100m"
            limits:
              memory: "10Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
          name: orders-backend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
