apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: orders-backend
spec:
    rules:
    - http:
        paths:
        - path: /backend
          pathType: Prefix
          backend:
            service:
              name: orders-backend
              port:
                number: 80